// Generated by FilterBuilder. http://htmlparser.org
// [aced0005737200206f72672e68746d6c7061727365722e66696c746572732e416e6446696c74657225a77ce23aa3c4110200015b000b6d5072656469636174657374001c5b4c6f72672f68746d6c7061727365722f4e6f646546696c7465723b78707572001c5b4c6f72672e68746d6c7061727365722e4e6f646546696c7465723b8f17479b1d5f7992020000787000000003737200246f72672e68746d6c7061727365722e66696c746572732e5461674e616d6546696c746572b28b2601a614890f0200014c00056d4e616d657400124c6a6176612f6c616e672f537472696e673b78707400025452737200296f72672e68746d6c7061727365722e66696c746572732e48617341747472696275746546696c74657296abdfb3b0714cda0200024c000a6d41747472696275746571007e00064c00066d56616c756571007e00067870740002696470737200256f72672e68746d6c7061727365722e66696c746572732e4861734368696c6446696c7465720d33e5cd9f31450e0200025a000a6d5265637572736976654c000c6d4368696c6446696c74657274001b4c6f72672f68746d6c7061727365722f4e6f646546696c7465723b7870007371007e00007571007e0003000000027371007e000574000254447371007e0009740005636c61737374000863617465676f7279]

import org.htmlparser.*;
import org.htmlparser.filters.*;
import org.htmlparser.beans.*;
import org.htmlparser.util.*;

public class Filter
{
    public static void main (String args[])
    {
        TagNameFilter filter0 = new TagNameFilter ();
        filter0.setName ("TR");
        HasAttributeFilter filter1 = new HasAttributeFilter ();
        filter1.setAttributeName ("id");
        TagNameFilter filter2 = new TagNameFilter ();
        filter2.setName ("TD");
        HasAttributeFilter filter3 = new HasAttributeFilter ();
        filter3.setAttributeName ("class");
        filter3.setAttributeValue ("category");
        NodeFilter[] array0 = new NodeFilter[2];
        array0[0] = filter2;
        array0[1] = filter3;
        AndFilter filter4 = new AndFilter ();
        filter4.setPredicates (array0);
        HasChildFilter filter5 = new HasChildFilter ();
        filter5.setRecursive (false);
        filter5.setChildFilter (filter4);
        NodeFilter[] array1 = new NodeFilter[3];
        array1[0] = filter0;
        array1[1] = filter1;
        array1[2] = filter5;
        AndFilter filter6 = new AndFilter ();
        filter6.setPredicates (array1);
        NodeFilter[] array2 = new NodeFilter[1];
        array2[0] = filter6;
        FilterBean bean = new FilterBean ();
        bean.setFilters (array2);
        if (0 != args.length)
        {
            bean.setURL (args[0]);
            System.out.println (bean.getNodes ().toHtml ());
        }
        else
            System.out.println ("Usage: java -classpath .;htmlparser.jar;htmllexer.jar Filter <url>");
    }
}
